class Shared{
    int num;
    boolean ready = false;
}

class Producer extends Thread{
    Shared s;

    Producer(Shared s){
        this.s = s;
    }

    public void run(){
        for (int i = 0; i < 10; i++){
            synchronized (s){
                while (s.ready){
                    try { s.wait(); } catch (Exception e) {}
                }

                s.num = (int)(Math.random() * 100) + 1;
                s.ready = true;

                System.out.println("Number generated by Producer: " + s.num);

                s.notify();
            }
        }
    }
}

class Consumer extends Thread{
    Shared s;
    int evenCount = 0;

    Consumer(Shared s){
        this.s = s;
    }

    public void run(){
        for (int i = 0; i < 10; i++){
            synchronized (s){
                while (!s.ready){
                    try { s.wait(); } catch (Exception e) {}
                }

                if (s.num % 2 == 0)
                    evenCount++;

                s.ready = false;
                s.notify();
            }
        }

        System.out.println("Number even numbers received by Consumer: " + evenCount);
    }
}

class ProConMain{
    public static void main(String[] args){
        Shared s = new Shared();

        new Producer(s).start();
        new Consumer(s).start();
    }
}
